
step 0: train loss 10.9873, val loss 10.9915
iter 0: loss 11.0254, time 22551.69ms, mfu -100.00%
iter 10: loss 10.9741, time 6902.59ms, mfu 4.88%
iter 20: loss 10.8277, time 6945.70ms, mfu 4.87%
iter 30: loss 10.6747, time 6972.17ms, mfu 4.87%
iter 40: loss 10.4401, time 6974.82ms, mfu 4.87%
iter 50: loss 10.2640, time 6964.32ms, mfu 4.86%
iter 60: loss 10.0220, time 6950.89ms, mfu 4.86%
iter 70: loss 9.9675, time 6974.01ms, mfu 4.86%
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/yxdong/anaconda3/envs/dyx-py38/lib/python3.8/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/home/yxdong/anaconda3/envs/dyx-py38/lib/python3.8/linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "/home/yxdong/anaconda3/envs/dyx-py38/lib/python3.8/tokenize.py", line 392, in open
    buffer = _builtin_open(filename, 'rb')
KeyboardInterrupt
Original exception was:
Traceback (most recent call last):
  File "train.py", line 382, in <module>
    logits, loss = model(X, Y)
  File "/home/yxdong/anaconda3/envs/dyx-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yxdong/anaconda3/envs/dyx-py38/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/yxdong/anaconda3/envs/dyx-py38/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/yxdong/anaconda3/envs/dyx-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yxdong/nano-gpt-test/nanoGPT-eva/model.py", line 181, in forward
    x = block(x)
  File "/home/yxdong/anaconda3/envs/dyx-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yxdong/nano-gpt-test/nanoGPT-eva/model.py", line 105, in forward
    x = x + self.mlp(self.ln_2(x))
  File "/home/yxdong/anaconda3/envs/dyx-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yxdong/nano-gpt-test/nanoGPT-eva/model.py", line 90, in forward
    x = self.c_proj(x)
  File "/home/yxdong/anaconda3/envs/dyx-py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1137, in _call_impl
    result = hook(self, input)
KeyboardInterrupt